# Generated by Django 5.2.4 on 2025-09-17 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_id",
                    models.BigIntegerField(unique=True, verbose_name="ID do Discord"),
                ),
                (
                    "discord_username",
                    models.CharField(max_length=100, verbose_name="Nome de Usuário"),
                ),
                (
                    "discord_display_name",
                    models.CharField(max_length=100, verbose_name="Nome de Exibição"),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL do Avatar"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Em Serviço"),
                            ("offline", "Fora de Serviço"),
                        ],
                        default="offline",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Novato"),
                            (2, "Aprendiz"),
                            (3, "Experiente"),
                            (4, "Veterano"),
                            (5, "Mestre"),
                        ],
                        default=1,
                        verbose_name="Nível",
                    ),
                ),
                ("points", models.IntegerField(default=0, verbose_name="Pontos")),
                (
                    "total_service_hours",
                    models.FloatField(
                        default=0.0, verbose_name="Horas Totais de Serviço"
                    ),
                ),
                (
                    "correct_votes",
                    models.IntegerField(default=0, verbose_name="Votos Corretos"),
                ),
                (
                    "incorrect_votes",
                    models.IntegerField(default=0, verbose_name="Votos Incorretos"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Última Atividade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guardião",
                "verbose_name_plural": "Guardiões",
                "ordering": ["-points", "-level"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.BigIntegerField(verbose_name="ID do Servidor")),
                ("channel_id", models.BigIntegerField(verbose_name="ID do Canal")),
                (
                    "reported_user_id",
                    models.BigIntegerField(verbose_name="ID do Usuário Denunciado"),
                ),
                (
                    "reporter_user_id",
                    models.BigIntegerField(verbose_name="ID do Denunciante"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Motivo"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("voting", "Em Votação"),
                            ("completed", "Concluída"),
                            ("appealed", "Em Apelação"),
                            ("closed", "Fechada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "punishment",
                    models.CharField(
                        choices=[
                            ("none", "Nenhuma"),
                            ("mute_1h", "Mute 1 hora"),
                            ("mute_12h", "Mute 12 horas"),
                            ("ban_24h", "Banimento 24 horas"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Punição",
                    ),
                ),
                (
                    "votes_improcedente",
                    models.IntegerField(default=0, verbose_name="Votos Improcedente"),
                ),
                (
                    "votes_intimidou",
                    models.IntegerField(default=0, verbose_name="Votos Intimidou"),
                ),
                (
                    "votes_grave",
                    models.IntegerField(default=0, verbose_name="Votos Grave"),
                ),
                (
                    "total_votes",
                    models.IntegerField(default=0, verbose_name="Total de Votos"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Denúncia",
                "verbose_name_plural": "Denúncias",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_user_id",
                    models.BigIntegerField(verbose_name="ID Original do Usuário"),
                ),
                (
                    "original_message_id",
                    models.BigIntegerField(verbose_name="ID Original da Mensagem"),
                ),
                (
                    "anonymized_username",
                    models.CharField(max_length=100, verbose_name="Nome Anonimizado"),
                ),
                ("content", models.TextField(verbose_name="Conteúdo da Mensagem")),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp")),
                (
                    "is_reported_user",
                    models.BooleanField(
                        default=False, verbose_name="É o Usuário Denunciado"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.report",
                        verbose_name="Denúncia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appellant_user_id",
                    models.BigIntegerField(verbose_name="ID do Apelante"),
                ),
                ("reason", models.TextField(verbose_name="Motivo da Apelação")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("voting", "Em Votação"),
                            ("approved", "Aprovada"),
                            ("rejected", "Rejeitada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "appeal_votes_improcedente",
                    models.IntegerField(
                        default=0, verbose_name="Votos Improcedente (Apelação)"
                    ),
                ),
                (
                    "appeal_votes_intimidou",
                    models.IntegerField(
                        default=0, verbose_name="Votos Intimidou (Apelação)"
                    ),
                ),
                (
                    "appeal_votes_grave",
                    models.IntegerField(
                        default=0, verbose_name="Votos Grave (Apelação)"
                    ),
                ),
                (
                    "appeal_total_votes",
                    models.IntegerField(
                        default=0, verbose_name="Total de Votos (Apelação)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeal",
                        to="core.report",
                        verbose_name="Denúncia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apelação",
                "verbose_name_plural": "Apelações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppealVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[
                            ("improcedente", "Improcedente"),
                            ("intimidou", "Intimidou"),
                            ("grave", "Grave"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Voto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "appeal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="core.appeal",
                        verbose_name="Apelação",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.guardian",
                        verbose_name="Guardião",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto de Apelação",
                "verbose_name_plural": "Votos de Apelação",
                "ordering": ["-created_at"],
                "unique_together": {("appeal", "guardian")},
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[
                            ("improcedente", "Improcedente"),
                            ("intimidou", "Intimidou"),
                            ("grave", "Grave"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Voto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.guardian",
                        verbose_name="Guardião",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="core.report",
                        verbose_name="Denúncia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto",
                "verbose_name_plural": "Votos",
                "ordering": ["-created_at"],
                "unique_together": {("report", "guardian")},
            },
        ),
    ]
