# Generated by Django 5.2.4 on 2025-09-17 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("assigned", "Atribuída"),
                            ("processing", "Processando"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="Prioridade")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Atribuída em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluída em"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.report",
                        verbose_name="Denúncia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fila de Denúncias",
                "verbose_name_plural": "Fila de Denúncias",
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="VotingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Aguardando Guardiões"),
                            ("voting", "Em Votação"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "voting_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Prazo para Votação"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.report",
                        verbose_name="Denúncia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de Votação",
                "verbose_name_plural": "Sessões de Votação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionGuardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ativo na Sessão"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Entrou em"),
                ),
                (
                    "left_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Saiu em"),
                ),
                (
                    "has_voted",
                    models.BooleanField(default=False, verbose_name="Já Votou"),
                ),
                (
                    "vote_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("improcedente", "Improcedente"),
                            ("intimidou", "Intimidou"),
                            ("grave", "Grave"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de Voto",
                    ),
                ),
                (
                    "voted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Votou em"
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.guardian",
                        verbose_name="Guardião",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.votingsession",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guardião da Sessão",
                "verbose_name_plural": "Guardiões da Sessão",
                "ordering": ["joined_at"],
                "unique_together": {("session", "guardian")},
            },
        ),
    ]
