# Generated by Django 5.2.4 on 2025-09-18 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_reportqueue_votingsession_sessionguardian"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("principios", "Os Princípios do Guardião"),
                            ("classificacao", "Classificando uma Denúncia"),
                            ("prova_final", "Prova Final"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Seção",
                    ),
                ),
                ("content", models.TextField(verbose_name="Conteúdo")),
                ("order", models.IntegerField(default=0, verbose_name="Ordem")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Seção de Treinamento",
                "verbose_name_plural": "Seções de Treinamento",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="guardian",
            name="discord_account_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Criação da Conta Discord"
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="role",
            field=models.CharField(
                choices=[("usuario", "Usuário"), ("guardian", "Guardião")],
                default="usuario",
                max_length=20,
                verbose_name="Papel",
            ),
        ),
        migrations.CreateModel(
            name="TrainingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Não Iniciado"),
                            ("in_progress", "Em Andamento"),
                            ("completed", "Concluído"),
                            ("failed", "Reprovado"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "exercises_completed",
                    models.IntegerField(
                        default=0, verbose_name="Exercícios Concluídos"
                    ),
                ),
                (
                    "exercises_correct",
                    models.IntegerField(default=0, verbose_name="Exercícios Corretos"),
                ),
                (
                    "final_exam_score",
                    models.IntegerField(
                        default=0, verbose_name="Pontuação da Prova Final"
                    ),
                ),
                (
                    "final_exam_attempts",
                    models.IntegerField(
                        default=0, verbose_name="Tentativas da Prova Final"
                    ),
                ),
                (
                    "last_exam_attempt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Tentativa da Prova"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_progress",
                        to="core.guardian",
                        verbose_name="Guardião",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.trainingsection",
                        verbose_name="Seção",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso do Treinamento",
                "verbose_name_plural": "Progressos do Treinamento",
                "ordering": ["guardian", "section__order"],
                "unique_together": {("guardian", "section")},
            },
        ),
        migrations.CreateModel(
            name="TrainingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Pergunta")),
                ("option_a", models.CharField(max_length=500, verbose_name="Opção A")),
                ("option_b", models.CharField(max_length=500, verbose_name="Opção B")),
                (
                    "option_c",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Opção C"
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("a", "A"), ("b", "B"), ("c", "C")],
                        max_length=1,
                        verbose_name="Resposta Correta",
                    ),
                ),
                ("explanation", models.TextField(verbose_name="Explicação")),
                ("order", models.IntegerField(default=0, verbose_name="Ordem")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="core.trainingsection",
                        verbose_name="Seção",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercício de Treinamento",
                "verbose_name_plural": "Exercícios de Treinamento",
                "ordering": ["section", "order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_answer",
                    models.CharField(
                        choices=[("a", "A"), ("b", "B"), ("c", "C")],
                        max_length=1,
                        verbose_name="Resposta Selecionada",
                    ),
                ),
                ("is_correct", models.BooleanField(verbose_name="Correta")),
                (
                    "answered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Respondido em"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.trainingexercise",
                        verbose_name="Exercício",
                    ),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.trainingprogress",
                        verbose_name="Progresso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta de Exercício",
                "verbose_name_plural": "Respostas de Exercícios",
                "ordering": ["answered_at"],
                "unique_together": {("progress", "exercise")},
            },
        ),
    ]
