# Generated by Django 5.2.4 on 2025-09-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_trainingsection_guardian_discord_account_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachments_info",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Informações dos Anexos"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="has_attachments",
            field=models.BooleanField(default=False, verbose_name="Tem Anexos"),
        ),
    ]
